version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Bob4158997"
      POSTGRES_DB: "ticketing-project-security"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data
    networks:
      - webnet
  ticketing-app:
    build: .
    platform: linux/amd64
    container_name: ticketingapp
    ports:
      - "1234:1234"
    networks:
      - webnet
    depends_on:
      - mypostgres
networks:
  webnet:
    driver: bridge
volumes:
  initdb:
