version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bob4158997"
      POSTGRES_DB: "ticketing-app1"
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - volumeToSaveDb:/var/lib/postgresql/data
    networks:
        - webnet
  ticketing-app:
    build: .
    container_name: ticketingapp
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - mypostgres
networks:
  webnet:
    driver: bridge
volumes:
  volumeToSaveDb:
