version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/home/circleci/project/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - /home/circleci/.m2
          key: v1-dependencies-{{ checksum "/home/circleci/project/pom.xml" }}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
