version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      # Set up the correct working directory for the project
      - run:
          name: Set up working directory
          command: mkdir -p /tmp/workspace
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/workspace/ticketing-project-security/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - /home/circleci/.m2
          key: v1-dependencies-{{ checksum "/tmp/workspace/ticketing-project-security/pom.xml" }}
      # Persist the workspace back to the project root
      - persist_to_workspace:
          root: /tmp/workspace
          paths: .
