version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/openjdk:11-jdk
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: /tmp/workspace/ticketing-project-security  # Specify the path to the project with pom.xml
      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - /tmp/workspace/ticketing-project-security/target
          key: v1-dependencies-{{ checksum "/tmp/workspace/ticketing-project-security/pom.xml" }}
      - persist_to_workspace:
          root: /tmp/workspace
          paths: .
